version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: contacts_db
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app_network

  app:
    build: .
    depends_on:
      - postgres
    environment:
      DB_URL: 'postgresql+asyncpg://postgres:db_password@postgres:5432/contacts_db'
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    networks:
      - app_network
    command: >
      sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  postgres-data:

networks:
  app_network:
    driver: bridge
